### PR TITLE
Allow step messages to be functions as well as strings

### PR DESCRIPTION
**Pull request by pgerlich**
## Problem:
You can not have dynamic values for 'messages' on steps, which makes it hard to create a truly dynamic user-driven conversation

## Solution:
Allow the message attribute of a step to be a callback which returns a string.

## Tests:
None updated

## Note:
For the future, it would be nice to have a callback on a step which is executed/waited on before moving to the next step. This callback should take the users message as an argument. This would create the 'legit' full-circle ability to have the chatbot dynamically communicate with users.

### CODE REVIEW

**Comment by LucasBassetti** [comment]
Hi, thanks for your interest in this project!

Did you try use the [Custom Step](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/steps)?

1. You can use the prop `asMessage` if you want rendered it as message
2. You can use the prop `waitAction` if you want wait some action

The [Custom Component](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/custom-component) will receive 4 props

1. `previousStep` - Previous step rendered
2. `Current step rendered` - Current step rendered
3. `steps` - All steps rendered
4. `triggerNextStep({ value, trigger })` - Callback function to trigger next step when user attribute is true. Optionally you can pass a object with value to be setted in the step and the next step to be triggered

Maybe you can create a dynamically with the custom step. You can user `waitAction` and after make some processing you should use the `triggerNextStep` callback to call the next step that you want. Optionally, you can render it as message using `asMessage` prop.

Did you consider to use that?

**Comment by pgerlich** [comment]
Yeah I don't want to have to create a custom component just to leverage these features. It would be nice to be able to bake dynamic responses/waiting into the existing component, as I don't necessarily agree that a custom component should be necessary.

With the custom component, can I be provided the users input from the last step as well?

**Comment by LucasBassetti** [comment]
How the message will be dynamic? You will need provide the previousValue as param, right?

Can you provide some example of dynamic responses/waiting?

Thanks!

**Comment by paulgerlich-wf** [comment]
Hey sorry, I actually ended up finding a better way to do this. The problem with this implementation was that the message would be the same for multiple messages.

I had 3 steps:
- 1 - Welcome message - 2
- 2 - User input - 3
- 3 - Bot Response - 2

And the issue is that each instance of step 3 would take on the most recent message, as it's the same instance of the step (instead of a clone)

This works as expected, but didn't fit my need.

I ended up using a custom component like you had mentioned.

**Comment by LucasBassetti** [comment]
Hi, no problem! But I like the option of message be a function as well and I like to implement that. I think it can be useful. The message will receive the `previousValue` and all `steps`. Some like  that:

```
{
    id: '1',
    message: ({ previousValue, steps }) => {
      return 'some string message';
    },
    end: true,
  },
```

**Comment by PSheon** [comment]
Hi ,Is it possible?

1 - Welcome message - 2
2 - User text input - (text === 'a') {trigger 3} else {trigger 4}

**Comment by LucasBassetti** [comment]
Hi @PSheon. Not yet but you give me an idea. Make the trigger a function as well. So, you will be able to trigger based on steps answers. Example:

```
{
   id: '1',
   user: true,
   trigger: ({ previousValue, steps }) => previousValue === 'a' ? '2' : '3',
}
```

**Comment by paulgerlich-wf** [comment]
Yeah that would be nice. Ideally we can do as much as possible without custom components. I found that my use was too complex to not use a custom component, unfortunately.

**Comment by LucasBassetti** [comment]
`trigger` as function added in `v0.2.6`

**Pull request merged**
