### PR TITLE
Adding a header font size param and chat box width param

### PR DESCRIPTION
**Pull request by chapmanc**
Very basic customizations that will help.

### CODE REVIEW

**Comment by LucasBassetti** [comment]
Hi, thanks for the PR! 

What do you think about change the name `chatBoxWidth` to just `width`?

**Comment by chapmanc** [comment]
I’d be okay with it but if we parametrize anything else and want specify its width it might not be the best? The width of the icon the width of the chat button. Agree/disagree?

**Comment by LucasBassetti** [comment]
Disagree. Because to me when I declare the chatbot I have:
```
<ChatBot
  steps={steps}
  width={width}
/>
```
So, I read ChatBot width. If the width is from other element I agree in put the name before. Like: buttonWidth (I read ChatBot button width).

**Comment by chapmanc** [comment]
Gotcha and updated.

**Comment by LucasBassetti** [comment]
Thank you!

**Comment by chapmanc** [comment]
Any chance of getting a new release ? Let me know what the timeline is if not :)

**Comment by LucasBassetti** [comment]
add `v0.2.7`

**Pull request merged**
