### PR TITLE
the chat can speak

### PR DESCRIPTION
**Pull request by puemos**

### CODE REVIEW

**Comment by LucasBassetti** [comment]
Hi @puemos, Thanks for the PR! I will check it ASAP.

In time, can you replace the lodash methods for pure javascript? I have intention to remove this dependency soon.

**Comment by puemos** [comment]
For sure! I prefer using the native API (I guessed that you wanted that way)

**Comment by puemos** [comment]
@LucasBassetti done! + added some tests

**Comment by LucasBassetti** [comment]
Amazing PR! Thank you!

**Pull request merged**
